//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface XCTestConfiguration : NSObject <NSSecureCoding>

@property(copy) NSURL *baselineFileURL;
@property BOOL disablePerformanceMetrics;
@property(copy) NSString *pathToXcodeReportingSocket;
@property(copy) NSString *productModuleName;
@property BOOL reportResultsToIDE;
@property(copy) NSUUID *sessionIdentifier;
@property(copy) NSString *targetApplicationBundleID;
@property(copy) NSString *targetApplicationPath;
@property(copy) NSURL *testBundleURL;
@property(copy) NSSet *testsToRun;
@property(copy) NSSet *testsToSkip;
@property BOOL treatMissingBaselinesAsFailures;

+ (id)activeTestConfiguration;
+ (id)configurationWithContentsOfFile:(id)arg1;
+ (void)setActiveTestConfiguration:(id)arg1;
+ (BOOL)supportsSecureCoding;

- (BOOL)writeToFile:(id)arg1;

@end
