//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol ISHDeviceInfo <NSObject>
@optional

+ (id)device;
+ (id)deviceWithPath:(id)arg1;

- (struct CGPoint)forceOrigin;
- (id)imageWithName:(id)arg1;
- (BOOL)isForcingSize;
- (id)newerEquivalent;
- (id)olderEquivalent;
- (double)pointHeight;
- (long long)priorityCompare:(id)arg1;
- (BOOL)supportsSDK:(id)arg1;

@property(copy) NSArray *additionalArguments;
@property(copy) NSDictionary *additionalEnvironment;
@property(readonly) NSString *architecture;
@property(copy) NSString *bundlePath;
@property BOOL canTether;
@property(copy) NSString *capabilitiesPlist;
@property(retain, nonatomic) NSImage *chromeImage;
@property(retain, nonatomic) NSImage *chromeImageDoubled;
@property(copy) NSString *chromeImageName;
@property(copy) NSString *chromeImageNameDoubled;
@property(copy) NSString *deviceBundle;
@property(copy) NSString *devicePitch;
@property(copy) NSString *displayName;
@property(readonly) double dotPitch;
@property(copy) NSString *executablePath;
@property struct CGSize forceSize;
@property(retain, nonatomic) NSImage *homeImage;
@property(retain, nonatomic) NSImage *homeImageDoubled;
@property(copy) NSString *homeImageName;
@property(copy) NSString *homeImageNameDoubled;
@property struct CGPoint homeOrigin;
@property struct CGPoint homeOriginDoubled;
@property(copy) NSString *identifier;
@property BOOL invertX;
@property BOOL invertY;
@property BOOL lp64;
@property(readonly) NSString *maximumSDK;
@property unsigned int maximumVersion;
@property(readonly) NSString *minimumSDK;
@property unsigned int minimumVersion;
@property(copy) NSString *newerEquivalentName;
@property(copy) NSString *olderEquivalentName;
@property long long priority;
@property(copy) NSString *productClass;
@property(copy) NSString *productFamily;
@property int productType;
@property BOOL rotateScreen180;
@property double scale;
@property struct CGSize size;
@property BOOL transformedTouch;
@property(readonly) NSSet *supportedArchitectures;

@end

#if XCODE_VERSION >= 0600
@interface ISHDeviceInfoStub : NSObject<ISHDeviceInfo>
@end
#else
@interface ISHDeviceInfo : NSObject<ISHDeviceInfo>
@end
@interface ISHDeviceInfoStub : ISHDeviceInfo
@end
#endif
