//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol ISHSDKInfo <NSObject>
@optional

- (instancetype)initWithRoot:(id)arg1;

@property(copy) NSString *fullVersionString;
@property(readonly) BOOL isComplete;
@property(readonly) void *libLaunchHostHandle;
@property(readonly) NSString *nameOfSpringBoardService;
@property(readonly) NSString *nameOfSystemAppService;
@property(readonly) NSString *nameOfWorkspaceService;
@property(readonly) NSDictionary *requiredHostServices;
@property(readonly) BOOL requiresAppMapRebuild;
@property(copy) NSString *root;
@property(copy) NSString *shortVersionString;
@property(readonly) BOOL supportsBootstrapSubset;
@property(readonly) BOOL supportsCar;
@property(readonly) BOOL supportsCloud;
@property(readonly) BOOL supportsHIDButtons;
@property(readonly) BOOL supportsLP64;
@property(readonly) BOOL supportsLaunchdSim;
@property(readonly) BOOL supportsStandaloneLog;
@property(readonly) BOOL supportsVisualQualityToggle;
@property(readonly) BOOL usesLegacyPathInfoStruct;
@property(readonly) BOOL usesLegacyPurpleTouchEvents;
@property(readonly) unsigned int version;

@end

#if XCODE_VERSION >= 0600
@interface ISHSDKInfoStub : NSObject<ISHSDKInfo>
@end
#else
@interface ISHSDKInfo : NSObject<ISHSDKInfo>
@end
@interface ISHSDKInfoStub : ISHSDKInfo
@end
#endif
