//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SimDeviceNotificationManager, SimServiceConnectionManager;

@interface SimDeviceSet : NSObject

+ (id)defaultSet;
+ (id)defaultSetPath;
+ (id)setForSetPath:(id)arg1;
- (instancetype)initWithSetPath:(id)arg1;

// properties
- (NSString *)setPath;

- (NSArray *)availableDevices;
- (NSArray *)devices;
- (NSDictionary *)devicesByUDID;
- (NSMutableDictionary *)devicesNotificationRegIDs;
- (NSObject *)devicesQueue;

- (SimServiceConnectionManager *)connectionManager;
- (SimDeviceNotificationManager *)notificationManager;

// others
- (void)addDevice:(id)arg1;
- (void)addDeviceAsync:(id)arg1;
- (void)createDeviceAsyncWithType:(id)arg1 runtime:(id)arg2 name:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)createDeviceWithType:(id)arg1 runtime:(id)arg2 name:(id)arg3 error:(id *)arg4;
- (id)defaultCreatedPlistPath;
- (BOOL)deleteDevice:(id)arg1 error:(id *)arg2;
- (void)deleteDeviceAsync:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)handleXPCNotification:(id)arg1;
- (void)handleXPCNotificationDeviceAdded:(id)arg1;
- (void)handleXPCNotificationDeviceRemoved:(id)arg1;
- (void)handleXPCRequest:(id)arg1 peer:(id)arg2;
- (void)handleXPCRequestCreateDevice:(id)arg1 peer:(id)arg2;
- (void)handleXPCRequestDeleteDevice:(id)arg1 peer:(id)arg2 device:(id)arg3;
- (unsigned long long)registerNotificationHandler:(CDUnknownBlockType)arg1;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)removeDeviceAsync:(id)arg1;
- (BOOL)unregisterNotificationHandler:(unsigned long long)arg1 error:(id *)arg2;
- (void)updateDefaultDevices;

@end
