//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface SimDeviceType : NSObject

+ (id)supportedDeviceTypes;
+ (id)supportedDeviceTypesByAlias;
+ (id)supportedDeviceTypesByIdentifier;
+ (id)supportedDevices;

- (instancetype)init;
- (instancetype)initWithBundle:(id)arg1;
- (instancetype)initWithPath:(id)arg1;

// properties
- (NSDictionary *)aliases;
- (NSBundle *)bundle;
- (NSDictionary *)capabilities;
- (NSDictionary *)environment_extra;
- (NSString *)identifier;
- (CGSize) mainScreenDPI;
- (float) mainScreenScale;
- (CGSize) mainScreenSize;
- (unsigned int) maxRuntimeVersion;
- (unsigned int) minRuntimeVersion;
- (NSString *)modelIdentifier;
- (NSString *)name;
- (NSString *)productClass;
- (NSString *)productFamily;
- (int) productFamilyID;
- (NSString *)springBoardConfigName;
- (NSArray *)supportedArchs;
- (NSDictionary *)supportedFeatures;
- (NSDictionary *)supportedFeaturesConditionalOnRuntime;
- (NSArray *)supportedProductFamilyIDs;

// getters
- (Class)deviceClass;
- (id)environment;
- (id)environmentForRuntime:(id)arg1;

// others
- (long long)compare:(id)arg1;
- (BOOL)supportsFeature:(id)arg1;
- (BOOL)supportsFeatureConditionally:(id)arg1;

@end
