//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface SimDeviceType : NSObject

+ (id)supportedDeviceTypes;
+ (id)supportedDeviceTypesByAlias;
+ (id)supportedDeviceTypesByIdentifier;
+ (id)supportedDeviceTypesByName;
+ (id)supportedDevices;

- (id)init;
- (id)initWithBundle:(id)arg1;
- (id)initWithPath:(id)arg1;

// properties
@property(copy) NSDictionary *aliases;
@property(retain) NSBundle *bundle;
@property(copy) NSDictionary *capabilities;
@property(copy) NSDictionary *environment_extra;
@property(copy) NSString *identifier;
@property struct CGSize mainScreenDPI;
@property float mainScreenScale;
@property struct CGSize mainScreenSize;
@property unsigned int maxRuntimeVersion;
@property unsigned int minRuntimeVersion;
@property(copy) NSString *modelIdentifier;
@property(copy) NSString *name;
@property(copy) NSString *productClass;
@property(readonly, copy) NSString *productFamily;
@property(readonly) int productFamilyID;
@property(copy) NSString *springBoardConfigName;
@property(copy) NSArray *supportedArchs;
@property(copy) NSDictionary *supportedFeatures;
@property(copy) NSDictionary *supportedFeaturesConditionalOnRuntime;
@property(copy) NSArray *supportedProductFamilyIDs;

// getters
- (Class)deviceClass;
- (id)environment;
- (id)environmentForRuntime:(id)arg1;

// others
- (long long)compare:(id)arg1;
- (BOOL)supportsFeature:(id)arg1;
- (BOOL)supportsFeatureConditionally:(id)arg1;

@end

