//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SimVerifier : NSObject

@property(retain) NSObject *serviceConnection;
@property(retain) NSObject *serviceConnectionQueue;

+ (id)connectionError;
+ (id)sharedVerifier;
+ (id)verificationError:(int)arg1;

- (id)verifyAll;
- (BOOL)verifyAllWithError:(id *)arg1;
- (id)verifyDyldSim:(id)arg1;

@end
