//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SimVerifier <NSObject>
@optional

@property(retain) NSObject *serviceConnection;
@property(retain) NSObject *serviceConnectionQueue;

+ (id)connectionError;
+ (id)sharedVerifier;
+ (id)verificationError:(int)arg1;

- (id)verifyAll;
- (BOOL)verifyAllWithError:(id *)arg1;
- (id)verifyDyldSim:(id)arg1;

@end

#if XCODE_VERSION < 0600
@interface SimVerifierStub : NSObject<SimVerifier>
@end
#else
@interface SimVerifier : NSObject<SimVerifier>
@end
@interface SimVerifierStub : SimVerifier
@end
#endif